#!/bin/sh
#adb shell kill -9 `adb shell ps | grep $1 | awk '{print $2}' `
FILENAME=temp.ps
adb shell ps | grep -i $1 > ${FILENAME}
LINE=`awk 'END{print NR}' ${FILENAME}`
if [ ${LINE} -eq 1 ] ;then
   echo "killing process: `awk '{print $9}' ${FILENAME}`"
   adb shell kill -9 `awk '{print $2}' ${FILENAME}`
else
   awk 'BEGIN{print "which process would be killed?"}
             {print NR,$0}' ${FILENAME}
   echo -n "[num]:"
   read NUM
   TARGETLINE=`sed -n ${NUM}p ${FILENAME}`
   echo "killiing process: `echo ${TARGETLINE} | awk '{print $9}'`"
   adb shell kill -9 `echo ${TARGETLINE} | awk '{print $2}'`
fi
rm ${FILENAME}
