#!/bin/sh

PUSH_PRIV_APP_CMD="adb push $1 system/priv-app"

if [ "`echo $1 | grep -ioE priv-app`" = "priv-app" ];then
  arg1=$1
  targetApk=${arg1##*/}
  echo "\n\n"
  echo "---------${targetApk}---------"

  if ${PUSH_PRIV_APP_CMD};then
    echo "push succeed"
  elif adb root;then
    adb wait-for-device
    adb remount
    ${PUSH_PRIV_APP_CMD}
  else
    echo "can not root"
  fi
fi
